#!/bin/sh

version=$1

git tag v$version

GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -o uchiwa-linux-amd64 .
GOOS=darwin CGO_ENABLED=0 GOARCH=amd64 go build -o uchiwa-darwin-amd64 .

npm install --production

zip -r public.zip public/

hub release create -a uchiwa-linux-amd64 -a uchiwa-darwin-amd64 \
  -a public.zip  v$version

rm uchiwa-*
rm public.zip
